# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pogo@AT124 < Formula
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "1.2.4"
  license "Zlib"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.2.4/pogo_Darwin_x86_64.tar.gz"
      sha256 "c75c4dfd6db92a591f69ec2d01cdbc5b08d508d28c030ef8a6e1dd9e832ee75b"

      def install
        bin.install "pogo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.2.4/pogo_Darwin_arm64.tar.gz"
      sha256 "fa2ac44d1050acd63e7f46933fc8b708479c64c8607a6efd6430cebf1fb3f728"

      def install
        bin.install "pogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.2.4/pogo_Linux_x86_64.tar.gz"
      sha256 "56b4a75ce9d47357e868d4e5fffa25c4e6ed510bfc37832349348090d8b7237d"
      def install
        bin.install "pogo"
      end
    end
  end
end
