# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pogo < Formula
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "2.1.0"
  license "Zlib"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pogo-vcs/pogo/releases/download/v2.1.0/pogo_Darwin_x86_64.tar.gz"
      sha256 "d8f82f61ec5157ba9ba3f1a3869cda9156fb9e7d8d82ae92eb63bd5bb8cedd49"

      def install
        bin.install "pogo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pogo-vcs/pogo/releases/download/v2.1.0/pogo_Darwin_arm64.tar.gz"
      sha256 "fe93ee0e48e7d9ab0862d645b70314c35cb4081bfd46fdaed299d16107b5407f"

      def install
        bin.install "pogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pogo-vcs/pogo/releases/download/v2.1.0/pogo_Linux_x86_64.tar.gz"
      sha256 "b66501da7f9581297fcd833f06143b9eea18fc556c9c03e6589c9425f3bf1ac1"
      def install
        bin.install "pogo"
      end
    end
  end
end
