# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pogo@AT201 < Formula
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "2.0.1"
  license "Zlib"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pogo-vcs/pogo/releases/download/v2.0.1/pogo_Darwin_x86_64.tar.gz"
      sha256 "b69b61393ca0febf5e882fd18d3618bcf8d17f853696c4e1584f11e54e12714b"

      def install
        bin.install "pogo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pogo-vcs/pogo/releases/download/v2.0.1/pogo_Darwin_arm64.tar.gz"
      sha256 "6ec51d6066f1c20071a3cc1b82308b24a3698a3eb9e7dff29b9abb81b9917f62"

      def install
        bin.install "pogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pogo-vcs/pogo/releases/download/v2.0.1/pogo_Linux_x86_64.tar.gz"
      sha256 "23b9ba5ec7a304d1e6bfe693619266f09ccc499060a9263029a533c4a5f186f6"
      def install
        bin.install "pogo"
      end
    end
  end
end
