# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pogo < Formula
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "1.5.0"
  license "Zlib"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.5.0/pogo_Darwin_x86_64.tar.gz"
      sha256 "c17840353870c682719ca6e965174ff784312af7675b5384abf4ae09535047e0"

      def install
        bin.install "pogo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.5.0/pogo_Darwin_arm64.tar.gz"
      sha256 "826fa672d5d4c21eb6691a7351506d1108dcbcf72630d06b7ced532cda823dd0"

      def install
        bin.install "pogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.5.0/pogo_Linux_x86_64.tar.gz"
      sha256 "bea7e12f52c860e4c34a71d2651c01e7e3e9676498ef986b5e89b42b13c633f3"
      def install
        bin.install "pogo"
      end
    end
  end
end
