# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pogo@AT120 < Formula
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "1.2.0"
  license "Zlib"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.2.0/pogo_Darwin_x86_64.tar.gz"
      sha256 "9f0db3f3dae30b4bc376acd121c75cd2d62cbe47876bddb666a8807b6683cbcb"

      def install
        bin.install "pogo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.2.0/pogo_Darwin_arm64.tar.gz"
      sha256 "8159b4a00aa92df03dc403279a15da9f575027b79f6f5760c2dd974a519a4b7c"

      def install
        bin.install "pogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.2.0/pogo_Linux_x86_64.tar.gz"
      sha256 "3937a0402005bc87964fc6b677e12415c2fff7c0653ca65247868494256e8d25"
      def install
        bin.install "pogo"
      end
    end
  end
end
