# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PogoAT1 < Formula
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "1.2.6"
  license "Zlib"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.2.6/pogo_Darwin_x86_64.tar.gz"
      sha256 "4cce73dc30bd3a343d2bc2c43fc70cb3322e06de3913658c49774404057dabd7"

      def install
        bin.install "pogo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.2.6/pogo_Darwin_arm64.tar.gz"
      sha256 "287584b21390ddab4bf73b08ba06403d98c9cd7c8e4d84565ce027587def5f6a"

      def install
        bin.install "pogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.2.6/pogo_Linux_x86_64.tar.gz"
      sha256 "f0cb0a5103c2e1963b39094a70caa3335193461406cb6aa90860f9495778300e"
      def install
        bin.install "pogo"
      end
    end
  end
end
