# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PogoAT1 < Formula
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "1.3.2"
  license "Zlib"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.3.2/pogo_Darwin_x86_64.tar.gz"
      sha256 "8432bab29e348aa406f11a04092249a4757ce5edb572613ea82d9bd246b8e221"

      def install
        bin.install "pogo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.3.2/pogo_Darwin_arm64.tar.gz"
      sha256 "7e97715dff34b5056dcfb8d9338a266a174206dc07f40d19f44c9c7b5a117403"

      def install
        bin.install "pogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.3.2/pogo_Linux_x86_64.tar.gz"
      sha256 "1f1c04af2ccf65d65f9d4b4a3d28fc682cb287ffa43714a2c0fb066df1b114cf"
      def install
        bin.install "pogo"
      end
    end
  end
end
