# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PogoAT1 < Formula
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "1.4.1"
  license "Zlib"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.4.1/pogo_Darwin_x86_64.tar.gz"
      sha256 "1bb951788301e713cbd9802385efbeac8c07023206684dfa9b44894ae4677fa3"

      def install
        bin.install "pogo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.4.1/pogo_Darwin_arm64.tar.gz"
      sha256 "f86a804d20ba6a26889828cc0a5da5f30fe6a140693d8236daa54ba536dde397"

      def install
        bin.install "pogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.4.1/pogo_Linux_x86_64.tar.gz"
      sha256 "4728cfef9043dc63dcfdb70ef3cd686f60de45dd28291bbec5cefb2ea56dddcf"
      def install
        bin.install "pogo"
      end
    end
  end
end
