# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pogo@AT151 < Formula
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "1.5.1"
  license "Zlib"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.5.1/pogo_Darwin_x86_64.tar.gz"
      sha256 "8db3552bc99919071a494ce6c6be7705e35fc1c11c1d95877be44123a185d6d5"

      def install
        bin.install "pogo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.5.1/pogo_Darwin_arm64.tar.gz"
      sha256 "e5f7d96bbbc8883d8cb725f2bf161a61bdf927042afaec17d70ce4d0cff37c38"

      def install
        bin.install "pogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pogo-vcs/pogo/releases/download/v1.5.1/pogo_Linux_x86_64.tar.gz"
      sha256 "9eee525367357eb7961bfe29c68086b148e495050ddbb1c834c72c8d9575a952"
      def install
        bin.install "pogo"
      end
    end
  end
end
