# This file was generated by GoReleaser. DO NOT EDIT.
cask "pogo" do
  name "pogo"
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "1.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pogo"
  manpage "docs/man/pogo-assets-delete.1"
  manpage "docs/man/pogo-assets-get.1"
  manpage "docs/man/pogo-assets-list.1"
  manpage "docs/man/pogo-assets-put.1"
  manpage "docs/man/pogo-assets.1"
  manpage "docs/man/pogo-bookmark-list.1"
  manpage "docs/man/pogo-bookmark-remove.1"
  manpage "docs/man/pogo-bookmark-set.1"
  manpage "docs/man/pogo-bookmark.1"
  manpage "docs/man/pogo-ci-runs-inspect.1"
  manpage "docs/man/pogo-ci-runs-list.1"
  manpage "docs/man/pogo-ci-runs.1"
  manpage "docs/man/pogo-ci-test.1"
  manpage "docs/man/pogo-ci.1"
  manpage "docs/man/pogo-clone.1"
  manpage "docs/man/pogo-commit.1"
  manpage "docs/man/pogo-completion-bash.1"
  manpage "docs/man/pogo-completion-fish.1"
  manpage "docs/man/pogo-completion-powershell.1"
  manpage "docs/man/pogo-completion-zsh.1"
  manpage "docs/man/pogo-completion.1"
  manpage "docs/man/pogo-describe.1"
  manpage "docs/man/pogo-diff.1"
  manpage "docs/man/pogo-discard.1"
  manpage "docs/man/pogo-edit.1"
  manpage "docs/man/pogo-gc.1"
  manpage "docs/man/pogo-gui.1"
  manpage "docs/man/pogo-info.1"
  manpage "docs/man/pogo-init.1"
  manpage "docs/man/pogo-invite-create.1"
  manpage "docs/man/pogo-invite-list.1"
  manpage "docs/man/pogo-invite.1"
  manpage "docs/man/pogo-log.1"
  manpage "docs/man/pogo-new.1"
  manpage "docs/man/pogo-push.1"
  manpage "docs/man/pogo-rm.1"
  manpage "docs/man/pogo-secrets-delete.1"
  manpage "docs/man/pogo-secrets-get.1"
  manpage "docs/man/pogo-secrets-list.1"
  manpage "docs/man/pogo-secrets-set.1"
  manpage "docs/man/pogo-secrets.1"
  manpage "docs/man/pogo-serve.1"
  manpage "docs/man/pogo-token-remove.1"
  manpage "docs/man/pogo-token-set.1"
  manpage "docs/man/pogo-token.1"
  manpage "docs/man/pogo-visibility.1"
  manpage "docs/man/pogo-whoami.1"
  manpage "docs/man/pogo.1"
  bash_completion "docs/completions/pogo.bash"
  zsh_completion "docs/completions/pogo.zsh"
  fish_completion "docs/completions/pogo.fish"

  on_macos do
    on_intel do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Darwin_x86_64.tar.gz"
      sha256 "8bd31c81872b35dc34604beef8f00a5fd30c22f87eb14a6a209037af3a55331f"
    end
    on_arm do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Darwin_arm64.tar.gz"
      sha256 "8890f2e599fcef7a5496e356bef398c94cfa5c814afa8b87f3620bd888d1888e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Linux_x86_64.tar.gz"
      sha256 "9a9a72a9b0fcfe6b608d39a7ac6cad39875db3533ebbf3c22522c2f502ff8f93"
    end
  end

  # No zap stanza required
end
