# This file was generated by GoReleaser. DO NOT EDIT.
cask "pogo@@0.11.0" do
  name "pogo@@0.11.0"
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "0.11.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pogo"
  manpage "docs/man/pogo-bookmark-list.1"
  manpage "docs/man/pogo-bookmark-remove.1"
  manpage "docs/man/pogo-bookmark-set.1"
  manpage "docs/man/pogo-bookmark.1"
  manpage "docs/man/pogo-ci-runs-inspect.1"
  manpage "docs/man/pogo-ci-runs-list.1"
  manpage "docs/man/pogo-ci-runs.1"
  manpage "docs/man/pogo-ci-test.1"
  manpage "docs/man/pogo-ci.1"
  manpage "docs/man/pogo-clone.1"
  manpage "docs/man/pogo-commit.1"
  manpage "docs/man/pogo-completion-bash.1"
  manpage "docs/man/pogo-completion-fish.1"
  manpage "docs/man/pogo-completion-powershell.1"
  manpage "docs/man/pogo-completion-zsh.1"
  manpage "docs/man/pogo-completion.1"
  manpage "docs/man/pogo-daemon-install.1"
  manpage "docs/man/pogo-daemon-run.1"
  manpage "docs/man/pogo-daemon-start.1"
  manpage "docs/man/pogo-daemon-stop.1"
  manpage "docs/man/pogo-daemon-uninstall.1"
  manpage "docs/man/pogo-daemon.1"
  manpage "docs/man/pogo-describe.1"
  manpage "docs/man/pogo-diff.1"
  manpage "docs/man/pogo-discard.1"
  manpage "docs/man/pogo-edit.1"
  manpage "docs/man/pogo-gc.1"
  manpage "docs/man/pogo-info.1"
  manpage "docs/man/pogo-init.1"
  manpage "docs/man/pogo-invite-create.1"
  manpage "docs/man/pogo-invite-list.1"
  manpage "docs/man/pogo-invite.1"
  manpage "docs/man/pogo-log.1"
  manpage "docs/man/pogo-new.1"
  manpage "docs/man/pogo-push.1"
  manpage "docs/man/pogo-rm.1"
  manpage "docs/man/pogo-secrets-delete.1"
  manpage "docs/man/pogo-secrets-get.1"
  manpage "docs/man/pogo-secrets-list.1"
  manpage "docs/man/pogo-secrets-set.1"
  manpage "docs/man/pogo-secrets.1"
  manpage "docs/man/pogo-serve.1"
  manpage "docs/man/pogo-token-remove.1"
  manpage "docs/man/pogo-token-set.1"
  manpage "docs/man/pogo-token.1"
  manpage "docs/man/pogo-visibility.1"
  manpage "docs/man/pogo-whoami.1"
  manpage "docs/man/pogo.1"
  bash_completion "docs/completions/pogo.bash"
  zsh_completion "docs/completions/pogo.zsh"
  fish_completion "docs/completions/pogo.fish"

  on_macos do
    on_intel do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Darwin_x86_64.tar.gz"
      sha256 "8ff53f68a24f9af32a5c87934e973992ad7737f0c00673346e928277707b2452"
    end
    on_arm do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Darwin_arm64.tar.gz"
      sha256 "5ba237ff9ecb09ed54b51e8d7fe38ad12ac93539ce66184c58f2da19c1e85a27"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Linux_x86_64.tar.gz"
      sha256 "eaceecf19a6e073af645d55e23a1c906ed36e4b1d2df8898a91721d3ce9efda7"
    end
    on_arm do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Linux_arm64.tar.gz"
      sha256 "58c4770e13df5f05873d58356522a1b966b985342476727f4de10fbc628b2cc8"
    end
  end

  # No zap stanza required
end
