# This file was generated by GoReleaser. DO NOT EDIT.
cask "pogo@0" do
  name "pogo@0"
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "0.12.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pogo"
  manpage "docs/man/pogo-bookmark-list.1"
  manpage "docs/man/pogo-bookmark-remove.1"
  manpage "docs/man/pogo-bookmark-set.1"
  manpage "docs/man/pogo-bookmark.1"
  manpage "docs/man/pogo-ci-runs-inspect.1"
  manpage "docs/man/pogo-ci-runs-list.1"
  manpage "docs/man/pogo-ci-runs.1"
  manpage "docs/man/pogo-ci-test.1"
  manpage "docs/man/pogo-ci.1"
  manpage "docs/man/pogo-clone.1"
  manpage "docs/man/pogo-commit.1"
  manpage "docs/man/pogo-completion-bash.1"
  manpage "docs/man/pogo-completion-fish.1"
  manpage "docs/man/pogo-completion-powershell.1"
  manpage "docs/man/pogo-completion-zsh.1"
  manpage "docs/man/pogo-completion.1"
  manpage "docs/man/pogo-daemon-install.1"
  manpage "docs/man/pogo-daemon-run.1"
  manpage "docs/man/pogo-daemon-start.1"
  manpage "docs/man/pogo-daemon-stop.1"
  manpage "docs/man/pogo-daemon-uninstall.1"
  manpage "docs/man/pogo-daemon.1"
  manpage "docs/man/pogo-describe.1"
  manpage "docs/man/pogo-diff.1"
  manpage "docs/man/pogo-discard.1"
  manpage "docs/man/pogo-edit.1"
  manpage "docs/man/pogo-gc.1"
  manpage "docs/man/pogo-info.1"
  manpage "docs/man/pogo-init.1"
  manpage "docs/man/pogo-invite-create.1"
  manpage "docs/man/pogo-invite-list.1"
  manpage "docs/man/pogo-invite.1"
  manpage "docs/man/pogo-log.1"
  manpage "docs/man/pogo-new.1"
  manpage "docs/man/pogo-push.1"
  manpage "docs/man/pogo-rm.1"
  manpage "docs/man/pogo-secrets-delete.1"
  manpage "docs/man/pogo-secrets-get.1"
  manpage "docs/man/pogo-secrets-list.1"
  manpage "docs/man/pogo-secrets-set.1"
  manpage "docs/man/pogo-secrets.1"
  manpage "docs/man/pogo-serve.1"
  manpage "docs/man/pogo-token-remove.1"
  manpage "docs/man/pogo-token-set.1"
  manpage "docs/man/pogo-token.1"
  manpage "docs/man/pogo-visibility.1"
  manpage "docs/man/pogo-whoami.1"
  manpage "docs/man/pogo.1"
  bash_completion "docs/completions/pogo.bash"
  zsh_completion "docs/completions/pogo.zsh"
  fish_completion "docs/completions/pogo.fish"

  on_macos do
    on_intel do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Darwin_x86_64.tar.gz"
      sha256 "d3573b103f1b8c14a9eab34cfeb1d8b2d7ef717cf845da4029eed63169b7f44b"
    end
    on_arm do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Darwin_arm64.tar.gz"
      sha256 "559eb7aa56a87dcf490df319e462500583b1ac96b15b04d86b2a620d36a8829d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Linux_x86_64.tar.gz"
      sha256 "962e85f61af832fd14ca2571b0b1b3d6090b77651328a8704b062713448e9dba"
    end
    on_arm do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Linux_arm64.tar.gz"
      sha256 "9cb14fa701052a01aefef55f578f3dca7af778ff39155a9ba33c05256d75a5d4"
    end
  end

  # No zap stanza required
end
