# This file was generated by GoReleaser. DO NOT EDIT.
cask "pogo@@1.5.1" do
  name "pogo@@1.5.1"
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "1.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pogo"
  manpage "docs/man/pogo-assets-delete.1"
  manpage "docs/man/pogo-assets-get.1"
  manpage "docs/man/pogo-assets-list.1"
  manpage "docs/man/pogo-assets-put.1"
  manpage "docs/man/pogo-assets.1"
  manpage "docs/man/pogo-bookmark-list.1"
  manpage "docs/man/pogo-bookmark-remove.1"
  manpage "docs/man/pogo-bookmark-set.1"
  manpage "docs/man/pogo-bookmark.1"
  manpage "docs/man/pogo-ci-runs-inspect.1"
  manpage "docs/man/pogo-ci-runs-list.1"
  manpage "docs/man/pogo-ci-runs.1"
  manpage "docs/man/pogo-ci-test.1"
  manpage "docs/man/pogo-ci.1"
  manpage "docs/man/pogo-clone.1"
  manpage "docs/man/pogo-commit.1"
  manpage "docs/man/pogo-completion-bash.1"
  manpage "docs/man/pogo-completion-fish.1"
  manpage "docs/man/pogo-completion-powershell.1"
  manpage "docs/man/pogo-completion-zsh.1"
  manpage "docs/man/pogo-completion.1"
  manpage "docs/man/pogo-describe.1"
  manpage "docs/man/pogo-diff.1"
  manpage "docs/man/pogo-discard.1"
  manpage "docs/man/pogo-edit.1"
  manpage "docs/man/pogo-gc.1"
  manpage "docs/man/pogo-gui.1"
  manpage "docs/man/pogo-info.1"
  manpage "docs/man/pogo-init.1"
  manpage "docs/man/pogo-invite-create.1"
  manpage "docs/man/pogo-invite-list.1"
  manpage "docs/man/pogo-invite.1"
  manpage "docs/man/pogo-log.1"
  manpage "docs/man/pogo-new.1"
  manpage "docs/man/pogo-push.1"
  manpage "docs/man/pogo-rm.1"
  manpage "docs/man/pogo-secrets-delete.1"
  manpage "docs/man/pogo-secrets-get.1"
  manpage "docs/man/pogo-secrets-list.1"
  manpage "docs/man/pogo-secrets-set.1"
  manpage "docs/man/pogo-secrets.1"
  manpage "docs/man/pogo-serve.1"
  manpage "docs/man/pogo-token-remove.1"
  manpage "docs/man/pogo-token-set.1"
  manpage "docs/man/pogo-token.1"
  manpage "docs/man/pogo-visibility.1"
  manpage "docs/man/pogo-whoami.1"
  manpage "docs/man/pogo.1"
  bash_completion "docs/completions/pogo.bash"
  zsh_completion "docs/completions/pogo.zsh"
  fish_completion "docs/completions/pogo.fish"

  on_macos do
    on_intel do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Darwin_x86_64.tar.gz"
      sha256 "8db3552bc99919071a494ce6c6be7705e35fc1c11c1d95877be44123a185d6d5"
    end
    on_arm do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Darwin_arm64.tar.gz"
      sha256 "e5f7d96bbbc8883d8cb725f2bf161a61bdf927042afaec17d70ce4d0cff37c38"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Linux_x86_64.tar.gz"
      sha256 "9eee525367357eb7961bfe29c68086b148e495050ddbb1c834c72c8d9575a952"
    end
  end

  # No zap stanza required
end
