# This file was generated by GoReleaser. DO NOT EDIT.
cask "pogo@0" do
  name "pogo@0"
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "0.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pogo"
  manpage "docs/man/pogo-bookmark-list.1"
  manpage "docs/man/pogo-bookmark-remove.1"
  manpage "docs/man/pogo-bookmark-set.1"
  manpage "docs/man/pogo-bookmark.1"
  manpage "docs/man/pogo-clone.1"
  manpage "docs/man/pogo-commit.1"
  manpage "docs/man/pogo-completion-bash.1"
  manpage "docs/man/pogo-completion-fish.1"
  manpage "docs/man/pogo-completion-powershell.1"
  manpage "docs/man/pogo-completion-zsh.1"
  manpage "docs/man/pogo-completion.1"
  manpage "docs/man/pogo-daemon-install.1"
  manpage "docs/man/pogo-daemon-run.1"
  manpage "docs/man/pogo-daemon-start.1"
  manpage "docs/man/pogo-daemon-stop.1"
  manpage "docs/man/pogo-daemon-uninstall.1"
  manpage "docs/man/pogo-daemon.1"
  manpage "docs/man/pogo-describe.1"
  manpage "docs/man/pogo-edit.1"
  manpage "docs/man/pogo-gc.1"
  manpage "docs/man/pogo-info.1"
  manpage "docs/man/pogo-init.1"
  manpage "docs/man/pogo-invite-create.1"
  manpage "docs/man/pogo-invite-list.1"
  manpage "docs/man/pogo-invite.1"
  manpage "docs/man/pogo-log.1"
  manpage "docs/man/pogo-new.1"
  manpage "docs/man/pogo-push.1"
  manpage "docs/man/pogo-rm.1"
  manpage "docs/man/pogo-serve.1"
  manpage "docs/man/pogo-token-remove.1"
  manpage "docs/man/pogo-token-set.1"
  manpage "docs/man/pogo-token.1"
  manpage "docs/man/pogo-whoami.1"
  manpage "docs/man/pogo.1"
  bash_completion "docs/completions/pogo.bash"
  zsh_completion "docs/completions/pogo.zsh"
  fish_completion "docs/completions/pogo.fish"

  on_macos do
    on_intel do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Darwin_x86_64.tar.gz"
      sha256 "e0c1658f4fd1b1615b2f207c20e40c2895a110ef2cb8ed7ee42816435e4c8a82"
    end
    on_arm do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Darwin_arm64.tar.gz"
      sha256 "e6cfe48272b0a56f3d10de232052ef0652155ada8303a716b40ca23503dce95a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Linux_x86_64.tar.gz"
      sha256 "b875f68fce4a7596e11a152a6bb602607c8ca52b0bfb6ee8f43ac82be0b91336"
    end
    on_arm do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Linux_arm64.tar.gz"
      sha256 "a9de791b3e5da1f5eb568c2bc0bc4c3dd0d80cc7e9c2bb7410227e4b36f7348a"
    end
  end

  # No zap stanza required
end
