# This file was generated by GoReleaser. DO NOT EDIT.
cask "pogo" do
  name "pogo"
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "0.14.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pogo"
  manpage "docs/man/pogo-bookmark-list.1"
  manpage "docs/man/pogo-bookmark-remove.1"
  manpage "docs/man/pogo-bookmark-set.1"
  manpage "docs/man/pogo-bookmark.1"
  manpage "docs/man/pogo-ci-runs-inspect.1"
  manpage "docs/man/pogo-ci-runs-list.1"
  manpage "docs/man/pogo-ci-runs.1"
  manpage "docs/man/pogo-ci-test.1"
  manpage "docs/man/pogo-ci.1"
  manpage "docs/man/pogo-clone.1"
  manpage "docs/man/pogo-commit.1"
  manpage "docs/man/pogo-completion-bash.1"
  manpage "docs/man/pogo-completion-fish.1"
  manpage "docs/man/pogo-completion-powershell.1"
  manpage "docs/man/pogo-completion-zsh.1"
  manpage "docs/man/pogo-completion.1"
  manpage "docs/man/pogo-daemon-install.1"
  manpage "docs/man/pogo-daemon-run.1"
  manpage "docs/man/pogo-daemon-start.1"
  manpage "docs/man/pogo-daemon-stop.1"
  manpage "docs/man/pogo-daemon-uninstall.1"
  manpage "docs/man/pogo-daemon.1"
  manpage "docs/man/pogo-describe.1"
  manpage "docs/man/pogo-diff.1"
  manpage "docs/man/pogo-discard.1"
  manpage "docs/man/pogo-edit.1"
  manpage "docs/man/pogo-gc.1"
  manpage "docs/man/pogo-info.1"
  manpage "docs/man/pogo-init.1"
  manpage "docs/man/pogo-invite-create.1"
  manpage "docs/man/pogo-invite-list.1"
  manpage "docs/man/pogo-invite.1"
  manpage "docs/man/pogo-log.1"
  manpage "docs/man/pogo-new.1"
  manpage "docs/man/pogo-push.1"
  manpage "docs/man/pogo-rm.1"
  manpage "docs/man/pogo-secrets-delete.1"
  manpage "docs/man/pogo-secrets-get.1"
  manpage "docs/man/pogo-secrets-list.1"
  manpage "docs/man/pogo-secrets-set.1"
  manpage "docs/man/pogo-secrets.1"
  manpage "docs/man/pogo-serve.1"
  manpage "docs/man/pogo-token-remove.1"
  manpage "docs/man/pogo-token-set.1"
  manpage "docs/man/pogo-token.1"
  manpage "docs/man/pogo-visibility.1"
  manpage "docs/man/pogo-whoami.1"
  manpage "docs/man/pogo.1"
  bash_completion "docs/completions/pogo.bash"
  zsh_completion "docs/completions/pogo.zsh"
  fish_completion "docs/completions/pogo.fish"

  on_macos do
    on_intel do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Darwin_x86_64.tar.gz"
      sha256 "ff0943eb31cdc1ae54301dc82792ff3d7c900dabc0f0733a35246d2ed95ae425"
    end
    on_arm do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Darwin_arm64.tar.gz"
      sha256 "3fa77e5e57beb97308bb2d74a89a62290a582be5a2a99409df5e2a126b09fa2e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Linux_x86_64.tar.gz"
      sha256 "4d417fb872270142517b27aa286e41346a71dea10bc78b59165328f23c77b40b"
    end
    on_arm do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Linux_arm64.tar.gz"
      sha256 "d4b7ccf052bdcd1fe3cf5376b6d11a7256de1ce00235cac680cc53aae100dd77"
    end
  end

  # No zap stanza required
end
