# This file was generated by GoReleaser. DO NOT EDIT.
cask "pogo@@0.1.0" do
  name "pogo@@0.1.0"
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pogo"
  manpage "docs/man/pogo-bookmark-list.1"
  manpage "docs/man/pogo-bookmark-set.1"
  manpage "docs/man/pogo-bookmark.1"
  manpage "docs/man/pogo-commit.1"
  manpage "docs/man/pogo-completion-bash.1"
  manpage "docs/man/pogo-completion-fish.1"
  manpage "docs/man/pogo-completion-powershell.1"
  manpage "docs/man/pogo-completion-zsh.1"
  manpage "docs/man/pogo-completion.1"
  manpage "docs/man/pogo-describe.1"
  manpage "docs/man/pogo-edit.1"
  manpage "docs/man/pogo-gc.1"
  manpage "docs/man/pogo-info.1"
  manpage "docs/man/pogo-init.1"
  manpage "docs/man/pogo-log.1"
  manpage "docs/man/pogo-new.1"
  manpage "docs/man/pogo-push.1"
  manpage "docs/man/pogo-rm.1"
  manpage "docs/man/pogo-serve.1"
  manpage "docs/man/pogo-token-remove.1"
  manpage "docs/man/pogo-token-set.1"
  manpage "docs/man/pogo-token.1"
  manpage "docs/man/pogo-whoami.1"
  manpage "docs/man/pogo.1"
  bash_completion "docs/completions/pogo.bash"
  zsh_completion "docs/completions/pogo.zsh"
  fish_completion "docs/completions/pogo.fish"

  on_macos do
    on_intel do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Darwin_x86_64.tar.gz"
      sha256 "2afe3137662933a5f7fa297664e95ef4b4b34f2580f5b0d5b8b6b1fba194913a"
    end
    on_arm do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Darwin_arm64.tar.gz"
      sha256 "04826cb601793d10d84caea65a86bac2adb969b62819ad7e63499aa26e7fb49b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Linux_x86_64.tar.gz"
      sha256 "306066be7126e0007b8768d7d258ac51c583b9741d7ed9b814c660a7a453dfd3"
    end
    on_arm do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Linux_arm64.tar.gz"
      sha256 "e364080c747e34139f310c58a5383d3e792d0017a4c1355e43d6a8fa1931fa83"
    end
  end

  # No zap stanza required
end
