# This file was generated by GoReleaser. DO NOT EDIT.
cask "pogo@@0.2.0" do
  name "pogo@@0.2.0"
  desc "A centralized version control system that is simple and easy to use."
  homepage "https://github.com/pogo-vcs/pogo"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pogo"
  manpage "docs/man/pogo-bookmark-list.1"
  manpage "docs/man/pogo-bookmark-remove.1"
  manpage "docs/man/pogo-bookmark-set.1"
  manpage "docs/man/pogo-bookmark.1"
  manpage "docs/man/pogo-clone.1"
  manpage "docs/man/pogo-commit.1"
  manpage "docs/man/pogo-completion-bash.1"
  manpage "docs/man/pogo-completion-fish.1"
  manpage "docs/man/pogo-completion-powershell.1"
  manpage "docs/man/pogo-completion-zsh.1"
  manpage "docs/man/pogo-completion.1"
  manpage "docs/man/pogo-describe.1"
  manpage "docs/man/pogo-edit.1"
  manpage "docs/man/pogo-gc.1"
  manpage "docs/man/pogo-info.1"
  manpage "docs/man/pogo-init.1"
  manpage "docs/man/pogo-log.1"
  manpage "docs/man/pogo-new.1"
  manpage "docs/man/pogo-push.1"
  manpage "docs/man/pogo-rm.1"
  manpage "docs/man/pogo-serve.1"
  manpage "docs/man/pogo-token-remove.1"
  manpage "docs/man/pogo-token-set.1"
  manpage "docs/man/pogo-token.1"
  manpage "docs/man/pogo-whoami.1"
  manpage "docs/man/pogo.1"
  bash_completion "docs/completions/pogo.bash"
  zsh_completion "docs/completions/pogo.zsh"
  fish_completion "docs/completions/pogo.fish"

  on_macos do
    on_intel do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Darwin_x86_64.tar.gz"
      sha256 "fce4270fd97d4effdd8d2e1f7b20721ea5e5b60772fc10c1b4a2cb3dc4413b07"
    end
    on_arm do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Darwin_arm64.tar.gz"
      sha256 "f23f4426bd20da35a3d353265aab165743ee6429ecb06dd360d7370a61d30b5a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Linux_x86_64.tar.gz"
      sha256 "fe507d642dfa712f98cb9f938c1d04d72783fdb6585d8e022afe4eabd7782cca"
    end
    on_arm do
      url "https://github.com/pogo-vcs/pogo/releases/download/v#{version}/pogo_Linux_arm64.tar.gz"
      sha256 "5bfef6a397998578ba5394cb9bbd9c612b7ef8f97588d17c3bef1020f084a4b3"
    end
  end

  # No zap stanza required
end
